services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:2.10-alpine@sha256:bf987a8729e1e71ce0696be799b9a1a392d413923c8462d63856c73d702c1a94
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=keycast,strfry
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - caddy_data:/data
    networks:
      - keycast
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  keycast:
    external: true
    name: keycast
  strfry:
    external: true
    name: strfry

volumes:
  caddy_data:
