[workspace]
members = ["api", "core", "signer"]
resolver = "2"

[workspace.dependencies]
base64 = "0.23.1"
chrono = { version = "0.4.45", features = ["serde"] }
nostr = { version = "=0.45.4", features = ["std", "os-rng", "nip04", "nip44", "nip46"] }
nostr-sdk = "=0.45.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sqlx = { package = "sqlx-core", version = "0.9.0", default-features = false, features = [ "_rt-tokio", "migrate", "chrono", "json" ] }
sqlx-sqlite = { version = "0.9.0", default-features = false, features = [ "bundled", "migrate", "chrono", "json" ] }
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
