[package]
name = "keycast_api"
description = "A Nostr key manager and remote signer"
authors = ["Keycast Authors"]
version.workspace = true
edition = "2021"

[dependencies]
axum = "0.8.9"
tower = { version = "0.5.3", features = ["util", "limit"] }
keycast_core = { path = "../core" }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tower-http = { version = "0.7.1", features = ["trace", "util", "cors"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
tower = { version = "0.5.3", features = ["util"] }
