[package]
name = "keycast_api"
description = "A Nostr key manager and remote signer"
authors = ["Keycast Authors"]
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.9"
tower = { version = "0.5.3", features = ["util", "limit"] }
base64 = { workspace = true }
chrono = { workspace = true }
keycast_core = { path = "../core" }
nostr = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha256 = "1.6.0"
sqlx = { workspace = true }
sqlx-sqlite = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tower-http = { version = "0.7.1", features = ["trace", "util", "cors"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
tower = { version = "0.5.3", features = ["util"] }
